- name: install deps
  apt:
    name: 
    - git
    - htop
    - ncdu
    - dstat
    - software-properties-common
    - net-tools
    state: latest
    update_cache: true
    
- name: Install certbot
  snap:
    name: certbot
    classic: true

- name: Set file permissions recursively
  file:
    path: /var/www/vhosts/
    owner: www-data
    group: www-data
    mode: "u=rwX,g=rwX,o=rX"
    recurse: yes
    state: directory
