- name: set passwords
  set_fact:
    root_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits!@#$%^*()-=+_') }}"
    db_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits!@#$%^*()-=+_') }}"

- include_tasks: dependencies.yml

- include_tasks: php.yml

- include_tasks: nginx.yml

- include_tasks: mysql.yml
